name: "minimal-versions"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        profile: minimal
    - run: rm ../Cargo.toml
      shell: bash
    - run: cargo update -Z minimal-versions
      shell: bash
    - run: cargo test --release
      shell: bash
    - run: cargo test --release --all-features
      shell: bash
