---
name: "cross-install"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    # yamllint disable rule:line-length
    - name: Install pre-compiled cross
      run: |
        export URL=$(curl --retry 10 -s https://api.github.com/repos/cross-rs/cross/releases/latest | \
          jq -r '.assets[] | select(.name | contains("x86_64-unknown-linux-gnu.tar.gz")) | .browser_download_url')
        wget -O /tmp/binaries.tar.gz $URL
        tar -C /tmp -xzf /tmp/binaries.tar.gz
        mv /tmp/cross ~/.cargo/bin
      shell: bash
