name: Install Debian (.deb) Packages
inputs:
  packages:
    description: space-separated list of Debian (.deb) packages to install
    required: true
runs:
  using: composite
  steps:
    - name: Update package index
      shell: bash
      run: sudo apt-get update
    - name: Install packages
      shell: bash
      env:
        DEBIAN_FRONTEND: noninteractive
      run: sudo apt-get install -y ${{ inputs.packages }}
